# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
        migrations.AddField(
            model_name='memberskill',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member'),
        ),
        migrations.AddField(
            model_name='memberskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Skill'),
        ),
    ]
