# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160806_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
