# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160806_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mentorship',
            field=models.ManyToManyField(related_name='related_to', through='app.Mentorship', to='app.Member'),
        ),
    ]
