# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160806_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
    ]
