# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-28 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160918_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together=set([('mentor', 'mentee')]),
        ),
    ]
